"use client";
import { useState } from "react";
import { ArrowUpRight, LoaderCircle } from "lucide-react";
import { serviceOptions } from "@/data/site";

export function LeadForm({ type }: { type: "audit" | "contact" }) {
  const [state, setState] = useState<"idle" | "sending" | "success" | "error">("idle"); const [message, setMessage] = useState("");
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); setState("sending"); const form = event.currentTarget; const payload = Object.fromEntries(new FormData(form)); try { const response = await fetch(`/api/${type}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json() as { success: boolean; message: string }; setMessage(data.message); setState(data.success ? "success" : "error"); if (data.success) form.reset(); } catch { setMessage("Something went wrong. Please email hello@mediamingles.com."); setState("error"); } }
  return <form className="lead-form" onSubmit={submit}><div className="lead-form__row"><label>Full name<input name="name" required minLength={2} autoComplete="name" placeholder="Your name" /></label><label>Email<input name="email" required type="email" autoComplete="email" placeholder="you@brand.com" /></label></div>{type === "audit" ? <label>Website or Instagram handle<input name="brand" placeholder="@yourbrand or yourbrand.com" /></label> : <label>Phone<input name="phone" autoComplete="tel" placeholder="Optional" /></label>}<label>What do you need help with?<select name="service" defaultValue="Not sure yet">{serviceOptions.map(item => <option key={item}>{item}</option>)}</select></label>{type === "contact" && <label>Message<textarea name="message" required minLength={10} rows={5} placeholder="Tell us about your brand and goals..." /></label>}<input className="honeypot" name="website" tabIndex={-1} autoComplete="off" aria-hidden="true" /><button disabled={state === "sending"} type="submit">{state === "sending" ? <LoaderCircle className="spin" /> : <>{type === "audit" ? "Request my free audit" : "Send message"}<ArrowUpRight /></>}</button>{message && <p className={`form-status form-status--${state}`} role="status">{message}</p>}</form>;
}
