"use client";
import { useRef, useState } from "react"; import { ArrowUpRight, LoaderCircle } from "lucide-react"; import { serviceOptions } from "@/data/site";
type FieldErrors = Record<string, string>;
export function LeadForm({ type }: { type: "audit" | "contact" }) {
  const [state, setState] = useState<"idle" | "sending" | "success" | "error">("idle"); const [message, setMessage] = useState(""); const [errors, setErrors] = useState<FieldErrors>({}); const formRef = useRef<HTMLFormElement>(null);
  function validate(form: HTMLFormElement) { const data = new FormData(form); const next: FieldErrors = {}; const name = String(data.get("name") || "").trim(); const email = String(data.get("email") || "").trim(); if (name.length < 2) next.name = "Enter at least 2 characters."; if (!/^\S+@\S+\.\S+$/.test(email)) next.email = "Enter a valid email address."; if (type === "contact" && String(data.get("message") || "").trim().length < 10) next.message = "Enter at least 10 characters."; return next; }
  async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const next = validate(form); setErrors(next); if (Object.keys(next).length) { setState("error"); setMessage("Please fix the highlighted fields."); requestAnimationFrame(() => form.querySelector<HTMLElement>(`[name="${Object.keys(next)[0]}"]`)?.focus()); return; } setState("sending"); setMessage(""); const payload = Object.fromEntries(new FormData(form)); try { const response = await fetch(`/api/${type}`, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(payload) }); const data = await response.json() as { success: boolean; message: string }; setMessage(response.status === 429 ? "Too many requests. Please wait a moment and try again." : data.message); setState(data.success ? "success" : "error"); if (data.success) { form.reset(); setErrors({}); } } catch { setMessage("We could not send this. Please email hello@mediamingles.com."); setState("error"); } }
  const error = (name: string) => errors[name] ? <span id={`${type}-${name}-error`} className="field-error">{errors[name]}</span> : null;
  return <form ref={formRef} className="lead-form" onSubmit={submit} noValidate><div className="lead-form__row"><label htmlFor={`${type}-name`}>Full name<input id={`${type}-name`} name="name" autoComplete="name" aria-invalid={!!errors.name} aria-describedby={errors.name ? `${type}-name-error` : undefined} />{error("name")}</label><label htmlFor={`${type}-email`}>Email<input id={`${type}-email`} name="email" type="email" autoComplete="email" aria-invalid={!!errors.email} aria-describedby={errors.email ? `${type}-email-error` : undefined} />{error("email")}</label></div>{type === "audit" ? <label htmlFor="audit-brand">Website or Instagram handle<input id="audit-brand" name="brand" placeholder="@yourbrand or yourbrand.com" /></label> : <label htmlFor="contact-phone">Phone <span>(optional)</span><input id="contact-phone" name="phone" autoComplete="tel" /></label>}<label htmlFor={`${type}-service`}>What do you need help with?<select id={`${type}-service`} name="service" defaultValue="Not sure yet">{serviceOptions.map(item => <option key={item}>{item}</option>)}</select></label>{type === "contact" && <label htmlFor="contact-message">Message<textarea id="contact-message" name="message" rows={5} aria-invalid={!!errors.message} aria-describedby={errors.message ? "contact-message-error" : undefined} />{error("message")}</label>}<input className="honeypot" name="website" tabIndex={-1} autoComplete="off" aria-hidden="true" /><button disabled={state === "sending"} type="submit">{state === "sending" ? <><LoaderCircle className="spin" /> Sending…</> : <>{type === "audit" ? "Request free audit" : "Send message"}<ArrowUpRight /></>}</button><p className={`form-status form-status--${state}`} role="status" aria-live="polite">{message}</p></form>;
}
